<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RD-jling" name="com.midian.webtest.use.MpublishFixedPrice" tests="1" failures="0" timestamp="12 Sep 2016 06:30:18 GMT" time="13.689" errors="1">
  <testcase name="publishFixedPrice" time="13.689" classname="com.midian.webtest.use.MpublishFixedPrice">
    <error type="java.lang.AssertionError" message="expected [发布成功！] but found [发布域名失败:该域名已经在交易中]">
      <![CDATA[java.lang.AssertionError: expected [发布成功！] but found [发布域名失败:该域名已经在交易中]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.midian.webtest.use.MpublishFixedPrice.publishFixedPrice(MpublishFixedPrice.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- publishFixedPrice -->
</testsuite> <!-- com.midian.webtest.use.MpublishFixedPrice -->
